### ISSUE TITLE
Name conflicts

### ISSUE THREAD

**Issue by mkutmon** [PathVisio/libGPML-old#10]
Currently in GPML2017 schema there are two element names used in different settings:
* Pathway.Author and Citations.Citation.Author
* Pathway.dataSource and Xref.dataSource

@ariutta do you see any problems with that?

**Comment by ariutta** [comment]
I thought we were getting rid of the attributes `Pathway.dataSource` and `Pathway.version`:
https://github.com/PathVisio/GPML/issues/19#issuecomment-320425452

If we aren't getting rid of them, we need to update [our vocab](https://vocabularies.wikipathways.org/gpml#version) to specify what we mean by `Pathway.version` and by `Pathway.dataSource` vs. `Xref.dataSource`:
https://github.com/PathVisio/GPML/issues/19#issuecomment-320343318

For `Author`, as long as we only use one element definition in the schema, it seems OK.

**Comment by Finterly** [comment]
In GPML 2021 Schema: 

Pathway.Author and Citations.Citation.Author --> Citations.Citation will no longer have Author
Pathway.dataSource and Xref.dataSource --> renamed to Pathway.source
