### ISSUE TITLE
Add type for TextLabels

### ISSUE THREAD

**Issue by DeniseSl22** [PathVisio/libGPML-old#18]
Currently, Labels do not have a Type; like the DataNodes do. This makes it difficult to do something extra with the Labels (adding a style to them in Cytoscape automated for example. Would be great to include this in 2017 schema.

**Comment by Finterly** [comment]
In GPML 2021 Schema changes, new DataNode types will be added such as: Metabolites, GeneProduct, DNA, RNA, Protein, Disease, Phenotype, etc. 

Pathway objects that were previously Labels fall under new DataNode type categories. Therefore Labels should be simply labels and will not need a type.
