### ISSUE TITLE
add annotation option for labels.

### ISSUE THREAD

**Issue by DeniseSl22** [PathVisio/libGPML-old#19]
We can now only annotate DataNodes with a database identifier. I would like to have this option available for textLabels as well (adding a <Xref Database="" ID="" /> to the schema). This can also be used to annotate additional information in a PW with Gene Ontology or other ontologies, disease database identifiers, AOP information etc.

**Comment by Finterly** [comment]
In GPML 2021 Schema, it will be possible to add additional information as Annotations to DataNodes, Labels, Shapes, States, Interactions, GraphicalLines, and Groups. 

Implementation: Annotations.Annotation.elementId is referred to by CommentGroup.AnnotationRef.elementRef.
