### ISSUE TITLE
Add location option in schema

### ISSUE THREAD

**Issue by DeniseSl22** [PathVisio/libGPML-old#20]
The (sub)cellular or tissue location for a DataNode (or TextLabel) would make a great addition to the schema. Perhaps something like:

<DataNode>
...
<Location>blablabla</Location>
...
</DataNode>

**Comment by Finterly** [comment]
In GPML 2021 Schema, it will be possible to add subcellular/tissue location information as Annotations to pathway elements DataNodes, Labels, etc. 

Implementation: Annotations.Annotation.elementId is referred to by CommentGroup.AnnotationRef.elementRef.
