### ISSUE TITLE
Allow State to have font data

### ISSUE THREAD

**Issue by saurabhkumar13** [PathVisio/libGPML-old#9]
In method updateFontData(), it is noted that State does not allow it.
@mkutmon  should this be fixed in the 2017 schema?

```java
protected void updateFontData(PathwayElement o, Element e) throws ConverterException
{
	String base = e.getName();
        setAttribute(base, "textLabel", e, o.getTextLabel());

	// TODO dirty hack: the fact that state doesn't allow font data is a bug 
	if (e.getName().equals ("State")) return;
```

**Comment by mkutmon** [comment]
would be nice to fix it. I am thinking about what kind of fontData a State would need. It probably doesn't need all of them, does it? What do you think?

**Comment by saurabhkumar13** [comment]
4c6d4273078832bb48026ee9f2c6cff3a97c5479

**Comment by Finterly** [comment]
In GPML 2021 Schema, State contains FontAttributes and thus has font data.
